### ISSUE TITLE
`numba` is also a dependency

### ISSUE THREAD

**Issue by berceanu** [hightower8083/synchrad#26]
It seems [`numba`](https://github.com/hightower8083/synchrad/blob/9320c0ad965764582e740ccb17f62c0e3e05e352/synchrad/converters.py#L4) should be added to the requirements file. 
Also, `openpmd_viewer` 1.X uses
`from openpmd_viewer import ..` instead of 
`from opmd_viewer import ..`, as stated in the README

**Comment by hightower8083** [comment]
hi @berceanu 

yes this part with `numba` import is assumed but is not correct. 
Actually `numba` is only used for a couple of secondary methods in converters and is not necessary for any actual `synchrad`'s functionality. I would prefer to keep `numba` dependency optional -- it's a big one and has its own specific relations to numpy. I've added handling of not-installed case with a warning
