### ISSUE TITLE
GitHub flow

### ISSUE THREAD

**Issue by berceanu** [hightower8083/synchrad#7]
Is there a particular reason for using a more complex `dev`/`master` model instead of the simpler [GitHub flow](https://guides.github.com/introduction/flow/) based on a single branch?

**Comment by berceanu** [comment]
See also [this answer](https://stackoverflow.com/questions/18188492/what-are-the-pros-and-cons-of-git-flow-vs-github-flow) on SO.

**Comment by hightower8083** [comment]
Hi Andrei, 
Well its not under intense development, so there is no specific strategy. I'm living mostly on dev and use branches for anything significant, and from time to time updating master
